mysite/urls.py
 
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('online_courses.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

online_courses/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.all_courses, name='all_courses'),
    path('authentication/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('authorization/', views.register_page, name='register'),
    path('profile/', views.user_profile, name='user_profile'),
    path('course/<int:pk>', views.course_details, name='course_details'),
    path('addmycourse/<int:pk>', views.add_to_my_courses, name='addmycourses'),
    path('delmycourse/<int:pk>', views.delete_from_my_courses, name='deletemycourses'),
    path('chats/<int:pk>/', views.every_chat, name='chat'),
    path('allchats/', views.all_chats, name='all_chats'),
    path('course/<int:pk>/theme/<int:thempk>', views.open_theme_course, name='full_course'),
    path('course/<int:pk>/theme/<int:thempk>/lection', views.course_lection, name='course_lection'),
    path('course/<int:pk>/theme/<int:thempk>/videolections', views.course_video, name='course_video'),
    path('course/<int:pk>/theme/<int:thempk>/test', views.course_test, name='course_test'),
    path('alltests/',views.all_tests,name='all_tests'),
    path('teacherscourses/',views.teacher_courses,name='teacher_courses'),
    path('addcourse/',views.addcourse,name='addcourse'),
    path('deletecourse/<int:pk>/',views.delete_course,name='deletecourse'),
    


    
]

online_courses/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Submition:
    correct=False
    question=''
    test_answer=''

class AllUserInfo(models.Model):
    user_pk = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    city=models.CharField(max_length=20,default='None')
    email=models.EmailField()
    phone=models.CharField(max_length=20,default='None')
    user_icon=models.ImageField(upload_to='icons/')
    user_type=models.CharField(max_length=30, default='student')
    def isUserTeacher(self):
        if(self.user_type == 'student'):
            return False
        else:
            return True
    def __str__(self):
        return self.first_name+ ' '+ self.last_name
    class Meta:
        verbose_name = "Қолданушы туралы толық ақпарат"
        verbose_name_plural = "Қолданушылар туралы толық ақпарат"

class CourseGeneral(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    info = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    course_icon = models.ImageField(upload_to='media/', blank=True ,default='qwert',null=True)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "Курс туралы толық ақпарат"
        verbose_name_plural = "Курстар туралы толық ақпарат"
class CourseParts(models.Model):
    course_pk=models.ForeignKey(CourseGeneral,on_delete=models.CASCADE)
    part_name=models.CharField(max_length=50)

class CourseSubject(models.Model):
    course_pk=models.ForeignKey(CourseGeneral,on_delete=models.CASCADE)
    subject_name=models.CharField(max_length=50)
    def __str__(self)  :
        return self.subject_name
    class Meta:
        verbose_name = "Тақырып"
        verbose_name_plural = "Тақыраптар"
class CourseLections(models.Model):
    subject_pk=models.ForeignKey(CourseSubject,on_delete=models.CASCADE)
    lection_title=models.CharField(max_length=50)
    lection_text1=models.TextField(default='')
    lection_text2=models.TextField(default='')
    lection_image=models.ImageField(upload_to='media/', blank=True ,default='qwert',null=True)
    def __str__(self) :
        return self.lection_title
    class Meta:
        verbose_name = "Лекция"
        verbose_name_plural = "Лекциялар"
class CourseVideoLections(models.Model):
    subject_pk=models.ForeignKey(CourseSubject,on_delete=models.CASCADE)
    lection_video=models.FileField(upload_to='videos/',null=True,blank=True)
    lection_title=models.CharField(max_length=50)

    def __str__(self):
        return self.lection_title
    class Meta:
        verbose_name = "Видео лекция"
        verbose_name_plural = "видео лекциялар"
class CourseTests(models.Model):
    course_pk=models.ForeignKey(CourseSubject,on_delete=models.CASCADE)
    test_question=models.TextField()
    test_option1=models.CharField(max_length=30)
    test_option2=models.CharField(max_length=30)
    test_option3=models.CharField(max_length=30)
    test_option4=models.CharField(max_length=30)
    test_answer=models.CharField(max_length=30)
    def __str__(self) :
        return self.test_question
    class Meta:
        verbose_name = "Тест"
        verbose_name_plural = "Тесттер"
class UserMessages(models.Model):
    user_sender=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE , related_name='user_sender')
    user_reciver=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='user_reciver')
    message_text=models.TextField()
    message_date=models.DateTimeField(default=timezone.now)

    def isCurrerntUserSender(self,curUser):
        if(self.user_sender.pk == curUser.pk):
            return True
        else:
            return False
    class Meta:
        verbose_name = "Хабарлама"
        verbose_name_plural = "Хабарламалар"
class UserTestResult(models.Model):
    user_pk=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    test_pk=models.ForeignKey(CourseSubject,on_delete=models.CASCADE)
    count_of_tests=models.IntegerField()
    count_correct=models.IntegerField()

    def getPercent(self):
        return self.count_correct / self.count_of_tests
    def __str__(self) :
        return self.user_pk + ' '+self.test_pk
    class Meta:
        verbose_name = "Тест нәтижесі"
        verbose_name_plural = "Тест нәтижелері"
class UserCourseSubscribe(models.Model):
    user_pk=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    course_pk=models.ForeignKey(CourseGeneral,on_delete=models.CASCADE)
    grades=models.IntegerField(default=0)
    def __str__(self) :
        return self.user_pk+' '+ self.course_pk
    class Meta:
        verbose_name = "Курсқа жазылым"
        verbose_name_plural = "Курстарға жазылым"


online_courses/views.py
from django.shortcuts import render
from .models import *
from .form import *
from django.contrib.auth import login,logout
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.db.models import Q

def all_courses(request):
    allCourses=CourseGeneral.objects.all()
    
    if( request.user.is_authenticated ):
        mycourses=UserCourseSubscribe.objects.filter(user_pk=request.user)
        userInfo=get_object_or_404( AllUserInfo,user_pk=request.user)
    else:
        mycourses={}
        userInfo={}
    return render(request, 'online_courses/index.html', {"courses":allCourses,"mycourses":mycourses,"userInfo":userInfo})

def login_page(request):
    if request.method=='POST':
        form=UserLoginform(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)

            return redirect('all_courses')
        else:
            messages.error(request,'Сіз электронды почтаны немесе құпия сөзді қате енгіздіңіз')
            form=UserLoginform()
    else:
        form=UserLoginform()
    
    return render(request,'online_courses/auth.html',{'form':form})
def logout_page(request):
    logout(request)
    return redirect('all_courses')
def register_page(request):
    if request.method=='POST':
        form=UserRegister(data=request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            AllUserInfo.objects.create(user_pk=user,
                                       first_name=user.first_name,
                                       last_name=user.last_name,
                                       email=user.username)
            col=send_mail(
               'Online Courses' ,
               'Добрый день! \n Вы успешно зарегистрированы в системе Online courses! Начните подготовку к ЕНТ с нами! \n С уважением, \nКоманда Online courses.kz',
                'bikesite@mail.ru',
                [str(user.username)],
                fail_silently=True 
            )
            return redirect('all_courses')
        else:
            messages.error(request,'Электронды почта тіркелген немесе құпия сөздер сәйкес келмейді')
            form=UserRegister()
    else:
        form=UserRegister()

    return render(request,'online_courses/register.html',{'form':form})
# gxo927fd986cdcwq8

def user_profile(request):
    info=AllUserInfo.objects.get(user_pk=request.user)
    if request.method == 'POST':  
        form = UserProfileForm(request.POST, request.FILES)  
        if form.is_valid():  
            AllUserInfo.objects.filter(user_pk=request.user).update(user_icon=form.instance.user_icon )
            return redirect('all_courses')
        else:
            form = UserProfileForm()
    else:
        form = UserProfileForm()
    return render(request,'online_courses/user-cabinet.html',{'user_info':info,'form':form})

def course_details(request,pk):
    course=get_object_or_404(CourseGeneral,pk=pk)
    all_subjects=CourseSubject.objects.filter(course_pk=course)
    if( request.user.is_authenticated ):

        subscribe=UserCourseSubscribe.objects.filter(user_pk=request.user.pk,course_pk=course)
        mycourses=UserCourseSubscribe.objects.filter(user_pk=request.user.pk)
        userInfo=AllUserInfo.objects.get(  user_pk=request.user.pk)

    else:
        subscribe={}
        mycourses={}
        userInfo={}
    return render(request,'online_courses/course-details.html',{'course':course ,'all_subjects':all_subjects ,'mycourses':mycourses,'userInfo':userInfo,'subscribe':subscribe})


def add_to_my_courses(request,pk):
    if( not request.user.is_authenticated ):
        return redirect('login')
    course=get_object_or_404(CourseGeneral,pk=pk)
    UserCourseSubscribe.objects.create(user_pk=request.user,course_pk=course)
    return redirect('course_details',pk=pk)

def delete_from_my_courses(request,pk):
    course=get_object_or_404(CourseGeneral,pk=pk)
    UserCourseSubscribe.objects.filter(user_pk=request.user,course_pk=course).delete()
    return redirect('course_details',pk=pk)

def all_chats(request):
    all_users=AllUserInfo.objects.filter().exclude(user_pk=request.user)
    mycourses=UserCourseSubscribe.objects.filter(user_pk=request.user)
    userInfo=get_object_or_404( AllUserInfo,user_pk=request.user)
    return render(request,'online_courses/all-chats.html',{"mycourses":mycourses,"userInfo":userInfo,'all_users':all_users})

def every_chat(request,pk):
    user=get_object_or_404( AllUserInfo,user_pk=request.user.pk)
    companion_user=get_object_or_404( AllUserInfo,user_pk=pk) 
    mycourses=UserCourseSubscribe.objects.filter(user_pk=request.user)
    if request.method=='POST':
        message_text=request.POST.get('text')
        UserMessages.objects.create(user_sender=request.user,user_reciver=companion_user.user_pk,message_text=message_text)
    chat_messages=UserMessages.objects.filter(Q(user_sender=request.user,user_reciver=companion_user.user_pk) | Q(user_sender=companion_user.user_pk,user_reciver=request.user)).order_by('-message_date')
    for messages in chat_messages:
        if messages.user_sender==request.user:
            messages.current_user=True
        else:
            messages.current_user=False
    return render(request,'online_courses/chat.html',{"userInfo":user,"companion_user":companion_user,'mycourses':mycourses,"messages":chat_messages})

def open_theme_course(request,pk,thempk):
    all_themes=CourseSubject.objects.filter(course_pk=pk)
    course=get_object_or_404(CourseGeneral,pk=pk)
    first_theme=CourseSubject.objects.get(pk=thempk)
    return render(request ,'online_courses/course-read.html',{'all_themes':all_themes,'course':course,'them':first_theme})
 
def course_lection(request,pk,thempk):
    all_themes=CourseSubject.objects.filter(course_pk=pk)
    course=get_object_or_404(CourseGeneral,pk=pk)
    first_theme=CourseSubject.objects.get(pk=thempk)
    lection=CourseLections.objects.get(subject_pk=thempk)
    return render(request ,'online_courses/course-lection.html',{'all_themes':all_themes,'course':course,'them':first_theme,'lection':lection})
 
def course_video(request,pk,thempk):
    all_themes=CourseSubject.objects.filter(course_pk=pk)
    course=get_object_or_404(CourseGeneral,pk=pk)
    first_theme=CourseSubject.objects.get(pk=thempk)
    video=CourseVideoLections.objects.get(subject_pk=thempk)
    return render(request ,'online_courses/course-video.html',{'all_themes':all_themes,'course':course,'them':first_theme,'video':video})
 


def course_test(request,pk,thempk):
    all_themes=CourseSubject.objects.filter(course_pk=pk)
    course=get_object_or_404(CourseGeneral,pk=pk)
    first_theme=CourseSubject.objects.get(pk=thempk)
    mycourses=UserCourseSubscribe.objects.filter(user_pk=request.user)
    userInfo=get_object_or_404( AllUserInfo,user_pk=request.user)
    alltests=CourseTests.objects.filter(course_pk=thempk)
    if request.method == 'POST':
        wrong=0
        correct=0
        total=0
        current_submission=[]
        for q in alltests:
            current=Submition()
            total+=1
            if q.test_answer ==  request.POST.get(q.test_question):
                correct+=1
                current.correct=True
            else:
                current.correct=False
                wrong+=1
            current.question=q.test_question
            current.test_answer=request.POST.get(q.test_question)
            current_submission.append(current)
        result=UserTestResult.objects.filter(user_pk=request.user,test_pk=first_theme)
        if(  len(result) == 0 ):
            result=UserTestResult.objects.create(user_pk=request.user,test_pk=first_theme,count_of_tests=total,count_correct=correct)
            ussub=UserCourseSubscribe.objects.get(user_pk=request.user,course_pk=course)
            UserCourseSubscribe.objects.filter(user_pk=request.user,course_pk=course).update(grades=ussub.grades+correct*5)
        
        return render(request ,'online_courses/test-result.html',{'current_submission':current_submission ,"mycourses":mycourses,'userInfo':userInfo})

    return render(request ,'online_courses/open-test.html',{'all_themes':all_themes,'course':course,'them':first_theme,'alltests':alltests , "mycourses":mycourses,'userInfo':userInfo})

def all_tests(request):
    if( not request.user.is_authenticated ):
        return redirect('login')
    userInfo=get_object_or_404( AllUserInfo,user_pk=request.user)

    mycourses=UserCourseSubscribe.objects.filter(user_pk=request.user.pk)
    for course in mycourses:
        subjects=CourseSubject.objects.filter(course_pk=course.course_pk)
        course.subject=subjects
    return render(request ,'online_courses/test.html',{"mycourses":mycourses,'userInfo':userInfo})

def teacher_courses(request):
    teacherCourses=CourseGeneral.objects.filter(author=request.user.pk)
    userInfo=AllUserInfo.objects.get(  user_pk=request.user.pk)
    for courses in teacherCourses:
        subscribers=UserCourseSubscribe.objects.filter(course_pk=courses.pk)
        courses.subscribers=subscribers
    return render(request, 'online_courses/teacher-main.html',{'teacherCourses':teacherCourses,'userInfo':userInfo})


def addcourse(request):
    
    if request.method == 'POST':
        courseform = CourseForm(request.POST)
        subjectform=SubjectForm(request.POST)
        lectionform=LectionForm(request.POST,request.FILES)
        videoform=VideoForm(request.POST,request.FILES)
        coursetests=CourseTestsForm(request.POST)

online_courses/templates/online_courses/add-course.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="">
    <link rel="stylesheet" href="{% static 'assets/css/second.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/add-course.css' %}">
</head>
<style>
#text{
    color: red;
}


</style>
<body>
    <main class="main-content">
        <div class="main-sidebar">
            <div class="main-sidebar__top">
                <img src="{% static  'assets/img/sidebar-right.jpg' %}" alt="">
            </div>
            <div class="main-sidebar__area">
                <h3>Курс материалы</h3>
                <div class="main-sidebar__area-anh">
                    <form class="main-sidebar-course-theme">
                        <span>
                            Бөлім 1
                        </span> 
                        <button>
                            <img src="assets/icon/musor-small.svg" alt="">
                        </button>
                    </form>
                    <a href="#"> + Жаңа бөлім қосу</a>
                    <a href="#"> + Ескертпелер</a>
                    <a href="#"> + Ресурстар</a>
                </div>
            </div>
        </div>

        <form action="" method="post" >

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger" role="alert" style="color: red;">
                        {{ message }}
                        </div>
                    {% else %}
                        <div  class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }} 
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% csrf_token %}
            <div class="main-area">
                <div class="main-area__top">
                     
                    <input type="text" placeholder="Жаңа курс ">
                </div>
                 <div class="main-theme-c-item-show">
                    <div class="main-theme-c-inp">
                        {{ courseform.as_p }}
                    </div>

                    <div class="main-theme-c-item__top">
                        {{  subjectform.as_p }}
                        <button><img src="{% static 'assets/icon/musor.svg' %}" alt=""></button>
                    </div>

                    <div class="main-theme-c-inp">
                        {{ lectionform.as_p }}

                         
                        <!-- <p>Видеолекция</> -->
                        {{videoform.as_p}}
                    </div>
                </div>
                <!-- тут выводишь добавленную тему -->
                
                 


                <div class="emtihan">
                    <div class="emtihan-quest">
                        <div class="emtihan-item">
                            {{ coursetests.test_question}}
                            <div class="emtihan-item__var">
                                <!-- <input type="text" placeholder="Нуска 1">
                                <input type="text" placeholder="Нуска 2">
                                <input type="text" placeholder="Нуска 3">
                                <input type="text" placeholder="Нуска 4"> -->

                                {% for test in  coursetests %}

                                    {{ test.label }}
                                    {{ test }}
                                    <br>
                                        {% for error in test.errors %}
                                            <div style="color: red;">{{ error }}</div>
                                        {% endfor %}
                                    {% endfor %}
                            </div>
                        </div>
                    </div>
                     
                </div>
                <button class="save" type="submit">Сақтау</button>
            </div>
        </form>
    </main>
    <button class="open-left__sidebar"> > </button>

    <script src="{% static 'assets/js/mobile-second.js' %}"></script>
    <script src="{% static 'assets/js/add-course.js' %}'></script>
</body>
</html>

online_courses/templates/online_courses/all-chats.html
{% extends 'online_courses/main.html' %}
{% load static %}


{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'assets/css/all-chats.css' %}">
</head>

        <div class="main-content">
            <h3>Барлық чаттар</h3>
            <div class="chat-search">
                <input type="text" placeholder="Іздеу">
                <button>Іздеу</button>
            </div>
            <div class="all-chat">
            {% for user in all_users %}
                <a href="{% url 'chat' pk=user.user_pk.pk %}" class="chat-item">

                    {% if user.user_icon %}
                        <img src="{{ user.user_icon.url }}" alt=""> 
                    {% else %}
                        <img src="assets/icon/chat.svg" alt=""> 
                    {% endif %}
                    <span>{{ user.first_name }} {{ user.last_name }}</span>
                </a>
                <!-- <a href="#" class="chat-item">
                    <img src="assets/icon/chat.svg" alt=""> <span>Аты Жөні</span>
                </a>
                <a href="#" class="chat-item">
                    <img src="assets/icon/chat.svg" alt=""> <span>Аты Жөні</span>
                </a> -->
            {% endfor %}
            </div>
            
        </div>
        {% endblock %}

online_courses/templates/online_courses/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'assets/css/auth.css' %}">
</head>
<body>
    
    <main class="auth">
        <div class="auth-left">
            <img src="{% static 'assets/img/ілім.png' %}" alt="">
            <div class="auth-circle"></div>
        </div>
        <div class="auth-right">
            <div class="auth-option">
                <a href="{% url 'login' %}" class="auth-login active">Kіру</a>
                <a href="{% url 'register' %}" class="auth-create">Тіркелу</a>
            </div>
            <form action="" method="post">
                <div class="auth-login__label">
                    {% csrf_token %}
                    {% for field in form %}
                        {{field}}
                    {% endfor %}
                    {% if messages %}
                        {% for message in messages|slice:":1" %}
                            <div class="alert alert-danger" role="alert" style="color: red;">
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <button class="auth-send" type="submit">Кіру</button>
                </div>
            </form>
            
        </div>
    </main>


    <script src="{% static 'assets/js/auth.js' %}"></script>
</body>
</html>

online_courses/templates/online_courses/course-details.html
{% extends 'online_courses/main.html' %}
{% load static %}


{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/course-details.css' %}">
</head>

        <div class="main-content">
            <div class="course-details">
                <div class="course-details__info">
                    <div class="course-details__info-left">
                        <h3> {{ course.title}} </h3>
                        <p>
                            {{ course.info }}
                        </p>
                    </div>
                    <div class="course-details__info-right">
                        <img src="{{ course.course_icon.url }}" alt="">
                        {% if subscribe %}
                        <div style="display: flex; flex-direction: row; justify-content: space-between; width: 250px;">
                            <a href="{% url 'deletemycourses' pk=course.pk  %} ">
                                <button style="background-color: #31465a;width: 90%;  " >Курстан бас тарту</button>
                            </a>  
                            <a href="{% url 'full_course' pk=course.pk  thempk=1 %}"><button style="width: 90%;" >Курсты оқу</button></a>  
                        </div>
                            {% else %}
                        <a href="{% url 'addmycourses' pk=course.pk  %}">
                            <button>Курсқа тіркелу</button>
                        </a>
                        {% endif %}
                    </div>
                </div>
                <div class="course-details__programm">
                    <h3>Курс бағдарламасы:</h3>
                    <ul>
                        {% for subject in all_subjects %}
                        <li>{{subject}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
{% endblock %}

online_courses/templates/online_courses/course-lection.html
{% extends 'online_courses/course-read.html' %}
{% load static %}





        {% block content %}
        <div class="main-area">
            <div class="main-area__top">{{ course.title }}</div>
            <div class="main-area__item">
                <div class="main-area__item-top">
                    <div class="main-area__item-title">
                        <span class="main-rotate"> > </span>
                        <span> Тақырып {{ lection }} </span>
                    </div>
                </div>
                <div class="main-area__item-info">
                    <p>{{ lection.lection_text1 }}</p>
                </div>
                <div class="main-area__item-info">
                    <h4>Мысал</h4>
                    <img src="{{ lection.lection_image.url }}" alt="">
                </div>
                <div class="main-area__item-info">
                    <p>{{ lection.lection_text1 }}</p>
                </div>
            </div>
            
           
        </div>
        {% endblock %}
     

online_courses/templates/online_courses/user-cabinet.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'assets/css/user-cabinet.css' %}">
</head>
<body>
    <main class="cabinet">
        <div class="sidebar">
            <div class="sidebar-photo">
                <label for="photo">
                    <img src="{% static 'assets/icon/avatar.png' %}" alt="">
                    <button>+</button>
                </label>
                <input id="photo" type="file">
            </div>
            <div class="sidebar-item">
                <a class="sidebar-item__active" href="">Жеке мәлімет</a>
                <a href="">Менің курстарым</a>
            </div>
        </div>
        <div class="cabinet-content">
            <div class="cabinet-content__top">
             
                
               
                    <a href="{% url 'all_courses'%}">
                        <button class="cabinet-content__help">
                        Кері қайту
                    </button>
                    </a>
                    
                
                <button class="cabinet-content__help">
                    Техниқалық қолдау
                </button>
                <a href="{%  url 'logout' %}">
                    <button>Шығу</button>
                </a>
                
            </div>
            <div class="cabinet-form">
                <form method="post" enctype="multipart/form-data">
                    <div class="cabinet-photo">
                        <label for="id_user_icon">
                            {%  if user_info.user_icon %}
                            <img src="{{ user_info.user_icon.url }}" alt="">
                            {% else %}
                            <img src="{% static 'assets/icon/avatar.png' %}" alt="">
                            {% endif %}
                            <button > +</button>
                        </label>
                       
                    </div>
                    {% csrf_token %}
                    {{ form.user_icon }}
                    <div class="cabinet-form__item">
                        <p>Аты</p>
                        <input type="text" value="{{ user_info.first_name }}" >
                    </div>
                    <div class="cabinet-form__item">
                        <p>Фамилия</p>
                        <input type="text" value="{{ user_info.last_name }}">
                    </div>
                    <div class="cabinet-form__item">
                        <p>Қала</p>
                        <input type="text">
                    </div>
                    <div class="cabinet-form__item">
                        <p>E-mail</p>
                        <input type="text" value="{{ user_info.email }}">
                    </div>
                    <div class="cabinet-form__item">
                        <p>Телефон</p>
                        <input type="text">
                    </div>
                    <button type="submit" >Сақтау</button>
                </form>
            </div>
        </div>
    </main>
</body>
</html>